import os
import random
import sys
import time
from time import sleep
os.system('clear')
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.4)
print ('loading..')
sleep(0.1)
mengetik('> > > > > > > > > > > > > > >] 100%')
sleep(1)
print
mengetik('WILUJENG SUMPING TI TOOLS. JIKA ADA KESALAHAN DALAM TOOLS KAMI SILAHKAN HUBUNGI ADMIN WHATSHAPP 088219478540 PIHAK KAMI AKAN MEMPERBAIKI TOOLS KAMI')
print
mengetik('Ketika seseorang menghina kamu, itu adalah sebuah pujian bahwa selama ini mereka menghabiskan banyak waktu ')
sleep(2)
os.system('clear')

print (colored("===========================================",'yellow'))
print (colored("Author : Mr XXXTRI3WSL",'green'))
print (colored("Youtube: AGUNG ZKYT",'blue'))
print (colored("Team   : NCPH - Network Crack",'green'))
print (colored("RECODE IZIN DULU KE: 088219478540",'blue'))
print (colored("===========================================",'yellow'))
print ("=====================   =====================")
print ("088219478540                 INDONESIA")
print ("=====================   =====================")
print ("     ==============================")
print ("             Mr.XXXTRI3WSL")
print ("                  AND")
print ("                Mrs.SITI")
print ("     ==============================")
sleep(3)
print
print (colored("==============================",'green'))
print (colored("1). VIRUS  ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("2). Hack-Fb-Premium ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("3).TROJANS ",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("4). HACK Fb Target ",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("5). HACK INSTRAGRAM ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("6). KUMPUPAN TOOLS HACK ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("7). INSTALL TOOLS ",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("8.). Hack Fb spider-fb",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("9).TamfanFacebook ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("10). CLONING YAHOO ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("11). HACK FACEBOOK. ",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("12). LITESPAM ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("13). INSTALL VIRUS ",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("14).TOOLSINSTALLERv3 TUANB4DUT",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("15). socialFish buat phising",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("16).Tampilan Termux Oh My Zsh",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("17). HACK WIFI ",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("18). SPAM TOL 1",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("19). MOD CAPING ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("20). Auto Like, Follow Instagram dan lain",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("21). tools milik Hack Bae",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("22). instahack.git ",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("23). SpamSmsTri Mr XXXTRI3WSL ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("24). Spam Wa ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("25).Tools INSTALL ADMIN FINDER",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("26). Tools INSTALL RED_HAWK ",'white'))
print (colored("==============================",'green'))
print (colored("27). CrackFB ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("28). Install metasploit ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("29). SpamCall",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("30). spam-sms",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("31). SpamOTP",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("32). DARK FB TERBARU ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("33). INSTALL Lazymux",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("34). Tools B4J1N64Nv5 ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("35).Tools userrecon ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("36). saycheese",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("37). bughunter",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("38). whatshack",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("39). Install Tools A-Rat ",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("40). Tools mrcakil ",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("41). FB-React ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("42).Tools kkktp Free ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("43). FHX-Hash-Killer ",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("44). PhisingGame.git ",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("45). AdminLogin ",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("46).    xl-py",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("47).     OSIF ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("48). Install Tools katoolin ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("49). santet-online",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("50). ddosWD ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("51). 404Tools ",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("52). HACK FBKU ",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("53). Tools Lacak ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("54). Tools BERGUNA UNTUK FB",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("55). Belajar Python3",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("56). DDOS SNIPER BLACKHAT TERSAKITI",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("57). Tools SADAP",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("58). DDOS ATTACK",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("59). Hack Fb no Brute",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("60). sdvspam ",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("61). BOM SPAM ",'white'))
print (colored("==============================",'green'))
sleep(1)
print (colored("62). INSTALL WEEMAN",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("63). SCANNER-INURLBR ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("64). MOD CASHTREE",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("65). PRANK CALL AND SPAM ",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("66). TEMBAK PAKET TELKOMSEL ",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("67). TEMBAK KUOTA ALL OPERATOR",'white'))
print (colored("==============================",'blue'))
sleep(1)
print (colored("68). BRUTEFORCE FB v.1",'white'))
print (colored("==============================",'red'))
sleep(1)
print (colored("69). BRUTEFORCE FB v.1.4",'white'))
print (colored("==============================",'yellow'))
sleep(1)
print (colored("70). AUTO KOMEN FACEBOOK",'white'))
print (colored("==============================",'blue'))
sleep(2)
pilih = str(input('[?] pilih : '))

if pilih == "1":
        os.system('pkg install git')
        os.system('pkg install python2')
        os.system('git clone https://github.com/justahackers/perusak')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]==================[+]")
        print ("[+]cd perusak")
        print ("[+]python2 perusak.py")
        print ("[+]==================[+]")
elif pilih == "2":
        os.system('pkg install git')
        os.system('pkg install python2')
        os.system('pip2 install mechanize')
        os.system('https://github.com/Bl4ckDr460n/Black-Fb-Premium')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]==================[+]")
        print ("[+]cd Black-Fb-Premium")
        print ("[+]python2 Black-Fb.py")
        print ("[+]==================[+]")
elif pilih == "3":
        os.system('pkg install git')
        os.system('pkf install python2')
        os.system('git clone https://github.com/R133F/Trojans')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]====================[+]")
        print ("[+]cd Trojans   ")
        print ("[+]chmod +x *   ")
        print ("[+]python2 trojans.py   ")
        print ("[+]====================[+]")
elif pilih == "4":
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('pip2 install requests')
        os.system('pip2 install mechanize')
        os.system('git clone https://github.com/FR13ND8/BRUTEFORCEnew')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=====================[+]")
        print ("[+]cd BRUTEFORCEnew     ")
        print ("[+]sh new.sh    ")
        print ("[+]=====================[+]")
elif pilih == "5":
        os.system('pkg install python2')
        os.system('pip2 install cowsay')
        os.system('pkg install cowsay')
        os.system('pkg install git')
        os.system('pkg install figlet')
        os.system('pkg install nano')
        os.system('git clone https://github.com/darkcurut08/darkcurut08')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=====================[+]")
        print ("[+]cd darkcurut08       ")
        print ("[+]sh Moreno77.sh       ")
        print ("[+]=====================[+]")
elif pilih == "6":
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('pip2 install requests')
        os.system('pip2 install mechanize')
        os.system('pip install termcolor')
        os.system ('https://github.com/MrXXXTRI3WSL/WORD.py')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=====================[+]")
        print ("[+]cd WORD.py   ")
        print ("[+]python3 WORD.py      ")
        print ("[+]=====================[+]")
elif pilih == "7":
        os.system('pkg install figlet')
        os.system('pkg install toilet')
        os.system('pkg install git')
        os.system('gem install lolcat')
        os.system('git clone https://github.com/MrXXXTRI3WSL/Install-Tools.sh')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]====================[+]")
        print ("[+]cd Install-Tools.sh  ")
        print ("[+]sh Install-Tools.sh  ")
        print ("[+]====================[+]")
elif pilih == "8":
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('pip2 install requests')
        os.system('pip2 install mechanize')
        os.system('git clone https:github.com/spider-fb/spider-fb')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]======================[+]")
        print ("[+]cd spider-fb     ")
        print ("[+]python2spider-fb.py]     ")
        print ("[+]======================[+]")
elif pilih == "9":
        os.system('apt update')
        os.system('apt upgrade')
        os.system('apt install php')
        os.system('apt install git')
        os.system('git clone https://github.com/MrTamfanX/TamfanFacebook')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]======================[+]")
        print ("[+]cd TamfanFacebook     ")
        print ("[+]chmod +x *  ")
        print ("[+]chmod -R 775 lib")
        print ("[+]sh tamfan.sh")
        print ("[+]======================[+]")
elif pilih == "10":
        os.system('pkg update && pkg upgrade')
        os.system('apt install git')
        os.system('pkg install python2')
        os.system('git clone https://github.com/dizart-y/cLONiNg-Yahoo')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]========================[+]")
        print ("[+]cLONiNg-Yahoo ")
        print ("[+]python2 CloningYahoo.py  ")
        print ("[+]========================[+]")
elif pilih == "11":
        os.system('pkg install python2')
        os.system('pip2 install requests')
        os.system('pip2 install mechanize')
        os.system('git clone https://github.com/MrXXXTRI3WSL/dkfb')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd dkfb   ")
        print ("[+] python2 FbHackV1.py   ")
        print ("[+]=======================[+]")
elif pilih == "12":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('git clone https://github.com/4L13199/LITESPAM')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd LITESPAM   ")
        print ("[+]sh LITESPAM.sh   ")
        print ("[+]=======================[+]")
elif pilih == "13":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/Hider5/Malicious')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd Malicious    ")
        print ("[+]chmod 777 malicious.py   ")
        print ("[+]python2 malicious.py")
        print ("[+]=======================[+]")
elif pilih == "14":
        os.system('pkg install php')
        os.system('pkg install curl')
        os.system('pkg install python2')
        os.system('git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv3')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd TOOLSINSTALLERv3   ")
        print ("[+]chmod +x TUANB4DUT.sh  ")
        print ("[+]sh TUANB4DUT.sh")
        print ("[+]=======================[+]")
elif pilih == "15":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install git')
        os.system('pkg install python2')
        os.system('pip2 install -r requirements.txt')
        os.system('pip2 install requests')
        os.system('pip install termcolor')
        os.system('git clone https://github.com/An0nUD4Y/SocialFish')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd SocialFish   ")
        print ("[+]python3 SocialFish.py   ")
        print ("[+]=======================[+]")
elif pilih == "16":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install git')
        os.system('pkg install python2')
        os.system('git clone https://github.com/Cabbagec/termux-ohmyzsh')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd termux-ohmyzsh   ")
        print ("[+]sh install.sh   ")
        print ("[+]=======================[+]")
elif pilih == "17":
        os.system('apt update')
        os.system('apt upgrade')
        os.system('apt install git')
        os.system('git clone https://github.com/esc0rtd3w/wifi-hacker')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd wifi-hacker  ")
        print ("[+]chmod +x wifi-hacker.sh  ")
        print ("[+]./wifi-hacker.sh")
        print ("[+]=======================[+]")
elif pilih == "18":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install git')
        os.system('pkg install python2')
        os.system(' git clone https://github.com/GUNAWAN18ID/B3604-spam-v1.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd B3604-spam-v1   ")
        print ("[+]bash B3604-spam.sh    ")
        print ("[+]=======================[+]")
elif pilih == "19":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install php')
        os.system('pkg install git')
        os.system('git clone https://github.com/anggaid14/caping')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd caping  ")
        print ("[+]php run.php   ")
        print ("[+]=======================[+]")
elif pilih == "20":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install git')
        os.system('pkg install nodejs')
        os.system('git clone http://github.com/rrudy0966/instatools')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd instatools    ")
        print ("[+]unzip node_modules.zip   ")
        print ("[+]pkg install nodejs lts")
        print ("[+]npm install instagram-private-api")
        print ("[+]node index")
        print ("[+]=======================[+]")
elif pilih == "21":
        os.system('pip2 install -r requirements.txt')
        os.system('pip2 install mechanize')
        os.system('pip2 install requests')
        os.system('pkg install openssh')
        os.system('pkg install Mtools')
        os.syatem('pip2 install Bs4')
        os.system('pip2 install urllib3 chardet certifi idna requests')
        os.system('git clone https://github.com/DICKYalone/dicky')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd dicky    ")
        print ("[+]sh Dickygt.sh    ")
        print ("[+]=======================[+]")
elif pilih == "22":
        os.system('apt update && apt upgrade')
        os.system('pkg install nano')
        os.system('pkg install python2')
        os.system('git clone https://github.com/avramit/instahack.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd instahack  ")
        print ("[+]pip install requests    ")
        print ("[+]cd instahack")
        print ("[+]nano pass.txt")
        print ("[+]cat pass.txt")
        print ("[+]python hackinsta.py")
        print ("[+]=======================[+]")
elif pilih == "23":
        os.system('pkg update && pkg upgrade')
        os.system('pip2 install requests')
        os.system('pip2 install mechanize')
        os.system('https://github.com/MrXXXTRI3WSL/SpamSmsTri')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd SpamSmsTri    ")
        print ("[+]php SpamSmsTri.php    ")
        print ("[+]=======================[+]")
elif pilih == "24":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/kumpulanremaja/spam-wa.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd spam wa   ")
        print ("[+]php wa.php    ")
        print ("[+]=======================[+]")
elif pilih == "25":
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('pip2 install mechanize')
        os.system('git clone https://github.com/Techzindia/admin_penal')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd admin_panel    ")
        print ("[+]chmod +x admin_panel_finder.py    ")
        print ("[+]python2 admin_panel_finder.py")
        print ("[+]=======================[+]")
elif pilih == "26":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/Tuhinshubhra/RED_HAWK')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd RED_HAWK ")
        print ("[+]chmod +x rhawk.php ")
        print ("[+]php rhawk.php")
        print ("[+]=======================[+]")
elif pilih == "27":
        os.system('apt update && apt upgrade')
        os.system('apt install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/MrXXXTRI3WSL/CrackFB')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd CrackFB ")
        print ("[+]python CRACKFB.py ")
        print ("[+]=======================[+]")
elif pilih == "28":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install php')
        os.system('git clone https://github.com/Hax4us/Metasploit_termux')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd metasploit-termux ")
        print ("[+]./metasploit.sh ")
        print ("[+]cd $HOME/metasploit-framework[+]")
        print ("[+]=======================[+]")
elif pilih == "29":
        os.system('pkg install python2')
        os.system('pip2 install requests')
        os.system('pip2 install mechanize')
        os.system('git clone https://github.com/storiku/Call')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print ("[+]cd Call")
        print ("[+]php spamcall.php")
        print ("[+]=======================[+]")
elif pilih == "30":
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('pip2 install mechanize')
        os.system('git clone https://github.com/kumpulanremaja/spam-sms.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd spam-sms ")
        print ("[+]bash spam.sh")
        print ("[+]=======================[+]")
elif pilih == "31":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/dz-id/SimpleSpamOtp')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd SimpleSpamOtp")
        print ("[+]php s-SpamOtp.php")
        print ("[+]=======================[+]")
elif pilih == "32":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('pkg install git')
        os.system('git clone https://github.com/ARIYA-CYBER/NEW')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]cd NEW")
        print ("[+]python2 FbNew.py")
        print ("[+]=======================[+]")
elif pilih == "33":
        os.system('pkg install git')
        os.system('pkg install python2')
        os.system('pkg install php')
        os.system('git clone https://github.com/Gameye98/Lazymux')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd Lazymux")
        print ("[+] chmod +x lazymux.py")
        print ("[+] python2 lazymux.py")
        print ("[+]=======================[+]")
elif pilih == "34":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clonehttps://github.com/DarknessCyberTeam/B4J1N64Nv5')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd B4J1N64Nv5")
        print ("[+] sh B4J1N64N.sh")
        print ("[+]=======================[+]")
elif pilih == "35":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/thelinuxchoice/userrecon')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd userrecon ")
        print ("[+] bash userrecon.sh")
        print ("[+]=======================[+]")
elif pilih == "36":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/thelinuxchoice/saycheese')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd saycheese")
        print ("[+] bash saycheese.sh ")
        print ("[+]=======================[+]")
elif pilih == "37":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/thehackingsage/bughunter.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd bughunter")
        print ("[+ ]chmod +x bughunter.py ")
        print ("[+]=======================[+]")
elif pilih == "38":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/AndriGanz/whatshack')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd whatshack ")
        print ("[+] sh  whatshack.sh( ")
        print ("[+]=======================[+]")
elif pilih == "39":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/Xi4u7/A-Rat')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd A-Rat ")
        print ("[+] chmod +x A-Rat.py")
        print ("[+] python2 A-Rat.py")
        print ("[+]=======================[+]")
elif pilih == "40":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/Mrcakil/mrcakil')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd mrcakil")
        print ("[+] chmod +x tools")
        print ("[+]./tools")
        print ("[+]=======================[+]")
elif pilih == "41":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/AMVengeance/FB-React.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] chmod +x FB-React -R ")
        print ("[+] cd FB-React")
        print ("[+] ./start")
        print ("[+]=======================[+]")
elif pilih == "42":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/IndonesianSecurity/kkktp')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd kkktp ")
        print ("[+] php kkktp.php ")
        print ("[+]=======================[+]")
elif pilih == "43":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/FajriHidayat088/FHX-Hash-Killer')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd FHX-Hash-Killer")
        print ("[+] python2 FHXHashKiller.py")
        print ("[+]=======================[+]")
elif pilih == "44":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/Senitopeng/PhisingGame.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd PhisingGame ")
        print ("[+] python2 phising.py")
        print ("[+]=======================[+]")
elif pilih == "45":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone http://github.com/AdheBolo/AdminLogin')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd AdminLogin ")
        print ("[+] python2 login.py")
        print ("[+]=======================[+]")
elif pilih == "46":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/albertoanggi/xl-py')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]====================[+]")
        print ("[+] pip install -r requirements.txt")
        print ("[+] chmod +x app.py ")
        print ("[+] python app.py")
        print ("[+]====================[+]")
elif pilih == "47":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/ciku370/OSIF')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]  cd OSIF")
        print ("[+] pip2 install -r requirements.txt")
        print ("[+] python2 osif.py")
        print ("[+]=======================[+]")
elif pilih == "48":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/LionSec/katoolin')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd katoolin  ")
        print ("[+] python2 katoolin.py")
        print ("[+]=======================[+]")
elif pilih == "49":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/Gameye98/santet-online')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]  santet-online")
        print ("[+] chmod +x ")
        print ("[+] python2 santet.py")
        print ("[+]=======================[+]")
elif pilih == "50":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/banghyuu/ddosWD')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]  cd ddosWD")
        print ("[+] sh Ddos.sh")
        print ("[+]=======================[+]")
elif pilih == "51":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clonehttps: //github.com/404system/404Tools')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd 404 Alat ")
        print ("[+] sh User.sh")
        print ("[+]=======================[+]")
elif pilih == "52":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/kangcoli/Fbku')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd Fbku  ")
        print ("[+] python2 Fbku.py")
        print ("[+]=======================[+]")
elif pilih == "53":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install python2')
        os.system('git clone https://github.com/thelinuxchoice/locator')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd locator ")
        print ("[+] bash locator.sh")
        print ("[+]=======================[+]")
elif pilih == "54":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/rahmadxyz/ToolsLengkap.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]  cd ToolsLengkap")
        print ("[+] sh rahmad.sh ")
        print ("[+]=======================[+]")
elif pilih == "55":
        os.system('pkg update && pkg upgrade')
        os.system('pkg inatall python2')
        os.system('pkg install git')
        os.system('git clonehttps://github.com/Tutorial-Termux-Hacking/Belajar_Python.V01')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd Belajar_Python.V01  ")
        print ("[+] python2 bahan.py")
        print ("[+] python2 Belajar_Python3.py ")
        print ("[+]=======================[+]")
elif pilih == "56":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/MrTamfanX/MCIDDOS')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd MCIDDOS  ")
        print ("[+] python2 TamfanDdos.py ")
        print ("[+]=======================[+]")
elif pilih == "57":
        os.system('pkg update && pkg upgrade')
        os.system('okg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/MrTamfanX/TamfanFacebook')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd TamfanFacebook ")
        print ("[+] chmod +x * ")
        print ("[+] chmod -R 775 lib")
        print ("[+] sh install.sh")
        print ("[+] sh tamfan.sh")
        print ("[+]=======================[+]")
elif pilih == "58":
        os.system('pkg update && pkg upgrade')
        os.system('pkg Install python')
        os.system('pkg install git')
        os.system('git clone https://github.com/cyweb/hammer')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] python hammer.py ")
        print ("[+]python hammer.py -s [IP target] -p [Port] -t 135 ")
        print ("[+]=======================[+]")
elif pilih == "59":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/0M3STG4NT3N6/refploit')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd refploit  ")
        print ("[+] chmod +x* ")
        print ("[+] bash rt.sh")
        print ("[+]=======================[+]")
elif pilih == "60":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/mrmsdv/sdvspam.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd sdvspam  ")
        print ("[+] sh install.sh")
        print ("[+] sh sdv.sh")
        print ("[+]=======================[+]")
elif pilih == "61":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/Amriez/gcospam')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd gcospam")
        print ("[+] sh install.sh")
        print ("[+] sh gco.sh")
        print ("[+]=======================[+]")
elif pilih == "62":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/evait-security/weeman.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd weeman ")
        print ("[+] python2 weeman.py")
        print ("[+]=======================[+]")
elif pilih == "63":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/googleinurl/SCANNER-INURLBR.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd SCANNER-INURLBR")
        print ("[+] php inurlbr.php")
        print ("[+]=======================[+]")
elif pilih == "64":
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('git clone https://github.com/radenvodka/cashtree')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd cashtree")
        print ("[+] nano cashtree.php")
        print ("[+] php cashtree.php ")
        print ("[+]=======================[+]")
elif pilih == "65":
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('pkg install figlet')
        os.system('git clone https://github.com/siputra12/prank')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+]  cd prank")
        print ("[+] php wa.php")
        print ("[+] php call.php")
        print ("[+]=======================[+]")
elif pilih == "66":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install git')
        os.system('pkg install php')
        os.system('git clone https://github.com/kumpulanremaja/tembaktelkomsel')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd telkomsel-api ")
        print ("[+] ")
        print ("[+]=======================[+]")
elif pilih == "67":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/Bintang73/tembaktembakan.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd tembaktembakan ")
        print ("[+] python dor.py")
        print ("[+]=======================[+]")
elif pilih == "68":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/FR13ND8/Fb-Cracker')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd Fb-Cracker-v.3  ")
        print ("[+] python2 crack.py ")
        print ("[+]=======================[+]")
elif pilih == "69":
        os.system('pkg install python2')
        os.system('pip2 install mechanize')
        os.system('pip2 install requests')
        os.system('git clone https://github.com/N1ght420/FaceBrute')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd FaceBrute ")
        print ("[+] python fb.py ")
        print ("[+]=======================[+]")
elif pilih == "70":
        os.system('pkg update && pkg upgrade')
        os.system('pkg install python2')
        os.system('pkg install git')
        os.system('git clone https://github.com/Senitopeng/Botkomena.git')
        print
        print ("=============================================")
        print (" IKUTI TULISAN DIBAWAH UNTUK JALANKAN script")
        print ("=============================================")
        print
        print ("[+]=======================[+]")
        print ("[+] cd Botkomena ")
        print ("[+] python2 botkomena.py")
        print ("[+]=======================[+]")